### PR TITLE
Update to Cura 5.0

### PR DESCRIPTION
**Pull request by Tim453**
Update all the dependencies #3 

- [x] PyQt to 6.2
- [x] Python dependencies to https://github.com/Ultimaker/cura-build-environment/blob/5.0-linux/projects/requirements.txt
- [x] Remove geos
- [x] Protobuf to 3.17.3
- [x] arcus to 5.0
- [ ] pynest2d to 5.0
- [x] savitar to 5.0
- [x] libCharon to 5.0
- [ ] Cura-engine to 5.0
- [ ] uranium to 5.0
- [ ] fdm_materials to 5.0
- [ ] cura to 5.0
- [ ] cura-binary-data to 5.0

### CODE REVIEW

**Comment by neildarlow** [comment]
Looks like some work needed to integrate the Sip module.

**Comment by Tim453** [comment]
> Looks like some work needed to integrate the Sip module.

Actually the sip module is already a part of `com.riverbankcomputing.PyQt.BaseApp`

**Comment by tapir** [comment]
Is there a time frame we can expect this? For arch, 5.0 appimages don't work anymore because they use ubuntu 20.04 as build platform and there is incompatibility between some libraries.

**Comment by neildarlow** [comment]
@tapir This is a big update and has suffered a few build failures. The arcus build is currently failed and pynest2d and uranium need to be updated successfully before the Cura-specific bits can be built,

I would imagine that this one will reside in the testing repository for a while too to highlight any new permission requirements and environmental issues which arise.

@Tim453 has a significant task on his hands and needs time to check his work carefully. Thank you @Tim453 for your efforts.

**Comment by Tim453** [comment]
@tapir this update will take some time, cause Ultimaker changed the entire way how Cura and all it's dependencies are build. They now use `conan` to install all the dependencies on their build machine. conan also generates CMakeFiles which then are used by the individual modules. The problem is that inside the Flatpak-build, there is no good way to use `conan`, because it requires a network connection (which we don't have in the flatpak-build process) to download all the build recipes and the dependencies.

Right now i have these ideas to solve these problems:
- Run the conan script outside of flatpak and then copy the `.conan` folder into the flatpak. (But the .conan folder is compressed around 60MB big, which i would have to store in this repository. It also contains the source code of different projects and we may run into legal problems)
- Just copy the generated CMakeFiles into the project and modify them so they can be used with the modules installed.
- Modify the CMakeFiles of Cura, Cura-engine, Pynest2d... to be compatible with libraries build.

**Comment by thopiekar** [comment]
You can test my package here: https://thopiekar.eu/2022/06/21/cura-rolled-out-as-flatpak/

Managed to get Cura packaged last weekend and got it fully working.

Building the engine was the biggest pain.

**Comment by neildarlow** [comment]
Thank you for your persistence at tackling this huge task. I will certainly be looking at this.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Tim453** [comment]
@thopiekar Great! I tried your build, it works fine. Only the [FDM Materials](https://github.com/ultimaker/fdm_materials) seems to be missing?

**Comment by thopiekar** [comment]
Yeah, noticed the same. I'm going to make an update soon.

**Comment by thopiekar** [comment]
Fix is online

**Comment by Tim453** [comment]
If you think your manifest is ready, you can create a new pull request. Then it can be published on Flathub.

**Comment by Tim453** [comment]
For now I will just use the AppImage and put it inside a Flatpak. I couldn't find a way to build Cura 5 from source with flatpak-builder. That means we will lose support for aarch64. But it will make the application easier maintainable.

**Comment by tapir** [comment]
FYI the libstd in the appimage won't work on newer distros and it needs to
be removed so that the system's own library is used instead

**Comment by neildarlow** [comment]
Are you sure about that? There are two AppImages and this flatpak specifies the one for newer Linux distributions.

The flatpak packaging of Cura 5.1.1 works fine on my fedora 37 Silverblue Pre-Release.

Regards,
Neil Darlow
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Tim453** [comment]
The Cura AppImage does not contain libstd. The Cura-Flatpak uses libstd of the Freedesktop Runtime, which is independent of the libstd version of your distro.

**Comment by neildarlow** [comment]
@Tim453 I took the query to be related to libstdc++ which is present in /app of the flatpak (libstdc++.so.6) so that's bundled.

**Comment by Tim453** [comment]
@neildarlow you are right. libstd is in the AppImage. What I wrote was wrong 🫣
@tapir Which distro are you using?

**Comment by tapir** [comment]
I'm on arch linux

**Comment by neildarlow** [comment]
No matter. I have transitioned from fedora 36 to fedora 37 Silverblue with the same Cura flatpak version in place and experienced to issues.

In fact, the presence of libstdc++ is likely to cause less issues than relying on the version present in the freedesktop.org runtime. Although the ABI compatibility level of both should be the same.

I don't see a need to remove libstdc++ but it's your call as maintainer.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Tim453** [comment]
@tapir I tried the Flatpak in Arch and did not experience any issues.

**Comment by tapir** [comment]
I was referring to old appimage. The newer one should work on new distros.
However now the flatpak won't work on older distros such as ubuntu 20.04.

**Comment by neildarlow** [comment]
@tapir Until @Tim453 is able to build the flatpak from source this will be an issue. The only solution, while using AppImages, would be to provide two flatpaks for both new and legacy distributions.

Hopefully the build issues will be solved soon - upstream have provided some suggestions e.g. disabling LTO for specific library build failures - and they need working through.

**Comment by Tim453** [comment]
The Flatpak should work on all distros. The new AppImage did not work on old distros, because it requires a recent glibc version. The Flatpak enviorment on the other hand is independent of the host glibc version, it uses glibc of the Freedesktop Runtime.

**Pull request merged**
