### PR TITLE
Bump to 5.6.0

### PR DESCRIPTION
**Pull request by Tim453**

### CODE REVIEW

**Comment by ToasterUwU** [comment]
What's needed for this to be done? If you need someone to test it, I would volunteer

**Comment by ToasterUwU** [comment]
not sure if you will see it without a direct ping, so here you go @Tim453

**Comment by Tim453** [comment]
Functionally it is working, but I cannot merge it because the check is waiting for a status report from the buildbot.

**Comment by Tim453** [comment]
bot, build

**Comment by Tim453** [comment]
Now the check passes, don't know why it was not working before.

**Pull request merged**
